# Generated by Django 2.1.3 on 2018-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviasearch', '0003_auto_20181110_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('length', models.CharField(max_length=400)),
                ('num_seats', models.IntegerField()),
                ('max_height', models.CharField(max_length=400)),
                ('speed', models.CharField(max_length=400)),
                ('max_weight', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='aviacompany',
            name='date',
            field=models.DateField(max_length=400),
        ),
    ]
